from gamera.core import *
from _typeshed import Incomplete
from gamera import util as util

class ClassifierStat:
    classifier: Incomplete
    path: Incomplete
    image_path: Incomplete
    max_size: Incomplete
    def __init__(self, classifier, path, max_size: int = ...) -> None: ...
    example_glyphs: Incomplete
    def make_example_glyphs(self) -> None: ...
    def make_grid(self, rows, cols): ...
    def make_pages(self) -> None: ...
    def make_html(self, filename, name, grid) -> None: ...
    def make_csv(self, filename, name, grid): ...

class ConfusionMatrix(ClassifierStat):
    title: str
    def make_result(self): ...

class ClassNameHistogram(ClassifierStat):
    title: str
    def make_result(self): ...

all_stat_pages: Incomplete

def make_stat_pages(classifier, path, pages: Incomplete | None = ..., max_size: int = ...) -> None: ...
