from gamera.core import *
from gamera import cluster as cluster, gamera_xml as gamera_xml, knn as knn, stats as stats

def max_distance(glyphs, k): ...
def local_max_distance(glyphs, x, k): ...
def get_graph_stats(glyphs, k): ...
def strip_small_categories(glyphs): ...
def test(): ...
