from .pyplate import *
from _typeshed import Incomplete
from gamera import args_wrappers as args_wrappers

def newer(source, target): ...
def magic_import(name, globals_: Incomplete | None = ..., locals_: Incomplete | None = ..., fromlist: Incomplete | None = ..., level: int = ...): ...
def magic_import_setup(ignore) -> None: ...
def restore_import() -> None: ...

template: Incomplete

def generate_plugin(plugin_filename, location, extra_compile_args: Incomplete | None = ..., extra_link_args: Incomplete | None = ..., define_macros: Incomplete | None = ...): ...
