from _typeshed import Incomplete
from gamera import util as util

class SymbolTable(util.CallbackObject):
    symbols: Incomplete
    def __init__(self) -> None: ...
    def add_callback(self, alert, callback) -> None: ...
    def normalize_symbol(self, symbol): ...
    def add(self, symbol, id: int = ...): ...
    def remove(self, symbol): ...
    def autocomplete(self, symbol): ...
    def exists(self, symbol): ...
