dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
addons:
  apt:
    packages:
    - djvulibre-bin
    - docbook-xml
    - docbook-xsl
    - exiv2
    - libboost-python-dev
    - libexempi3
    - libexiv2-dev
    - libpng-dev
    - libtiff4-dev
    - libxml2-utils
    - minidjvu
    - xsltproc
cache:
  directories:
  - $HOME/.cache
  - $HOME/.ccache
env:
- GAMERA_VERSION=3.4.3
before_install:
- pillow_suffix===4.3.0
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pillow_suffix===3.4.2; fi
install:
- export PATH="/usr/lib/ccache:$PATH"
- wget -c https://github.com/hsnr-gamera/gamera/releases/download/$GAMERA_VERSION/gamera-${GAMERA_VERSION}.tar.gz -O ~/.cache/gamera-${GAMERA_VERSION}.tar.gz
- tar -xvzf ~/.cache/gamera-${GAMERA_VERSION}.tar.gz
- sed -i -e 's/no_wx = False/no_wx = True/' gamera-${GAMERA_VERSION}/setup.py
- ( cd gamera-${GAMERA_VERSION}/ && python setup.py install )
- rm -r gamera-${GAMERA_VERSION}/
- pip install --verbose pillow${pillow_suffix}
- pip install python-xmp-toolkit
- pip install --verbose git+https://github.com/escaped/pyexiv2
- pip install pydiatra pyflakes
- pip install docutils pygments
script:
- nosetests -v
- py2diatra .
- pyflakes .
- private/check-rst
- xmllint --nonet --noout --valid doc/*.xml
- python setup.py install
- cd /
- didjvu --version
- export MANPATH="$VIRTUAL_ENV/share/man" MANWIDTH=80
- man 1 didjvu | grep -A 10 -w DIDJVU
- curl -fsS https://pypi.org/simple/didjvu/; [ $? -eq 22 ]

# vim:ts=2 sts=2 sw=2 et
