dist: xenial
language: python
addons:
  apt:
    packages: &packages
    - djvulibre-bin
    - docbook-xml
    - docbook-xsl
    - exiv2
    - gir1.2-gexiv2-0.10
    - libboost-python-dev
    - libexempi3
    - libexiv2-dev
    - libpng-dev
    - libtiff-dev
    - libxml2-utils
    - minidjvu
    - python-gi
    - xsltproc
jobs:
  include:
  - python: "2.7"
    env:
    - GAMERA_VERSION=3.3.2
    - PILLOW=3.4.2
    addons:
      apt:
        packages:
        - *packages
        - g++-4.6
    dist: trusty
  - python: "2.7"
    env: GAMERA_VERSION=3.4.3
cache:
  pip: true
  directories:
  - $HOME/.ccache
before_install:
- gamera_url="https://github.com/hsnr-gamera/gamera/releases/download/$GAMERA_VERSION/gamera-${GAMERA_VERSION}.tar.gz";
- if [[ $GAMERA_VERSION = 3.3.2 ]]; then
    gamera_url="https://github.com/hsnr-gamera/gamera/archive/173cbefd7046a526c9238c337c15dc75bef42924.tar.gz";
    export CC=gcc-4.6;
    export CXX=g++-4.6;
  fi
- gexiv2_version=$(dpkg-query -Wf '${source:Version}' gir1.2-gexiv2-0.10)
- if [[ $gexiv2_version = 0.10.[3-9]* ]]; then if_pyexiv2=:; else if_gexiv2=:; fi
- export PATH="/usr/lib/ccache:$PATH"
install:
- wget "$gamera_url" -O "gamera-${GAMERA_VERSION}.tar.gz"
- tar -xvzf gamera-*.tar.gz
- ( cd gamera-*/ && echo '__version__ = "0.0"' > wx.py)
- ( cd gamera-*/ && python setup.py install )
- rm -r gamera-*
- pip install --verbose pillow${PILLOW:+==$PILLOW}
- pip install python-xmp-toolkit
- $if_pyexiv2 pip install --verbose git+https://github.com/escaped/pyexiv2
- $if_gexiv2 cp -a /usr/lib/python2.7/dist-packages/gi $VIRTUAL_ENV/lib/python2.7/site-packages/
- $if_gexiv2 mv -v $VIRTUAL_ENV/lib/python2.7/site-packages/gi/_gi{.x86_64-linux-gnu,}.so
- pip install pydiatra
- pip install pyflakes
- pip install docutils pygments
script:
- make test
- py2diatra .
- pyflakes .
- make -C doc check
- make -C doc all
- make install PREFIX=$HOME/.local
- cd /
- didjvu --version
- export MANPATH="$HOME/.local/share/man" MANWIDTH=80
- man 1 didjvu | grep -A 10 -w DIDJVU
- curl -fsS https://pypi.org/simple/didjvu/; [ $? -eq 22 ]

# vim:ts=2 sts=2 sw=2 et
