language: python
python:
- "2.6"
- "2.7"
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y djvulibre-bin minidjvu
- sudo apt-get install -y libtiff-dev libpng-dev
- sudo apt-get install -y libexempi3
- sudo apt-get install -y libexiv2-dev libboost-python-dev
- sudo apt-get install -y exiv2
install:
- pip install docutils
- pip install pygments
- wget http://sourceforge.net/projects/gamera/files/gamera/gamera-3.4.2/gamera-3.4.2.tar.gz -O /tmp/gamera.tar.gz
- tar -xvzf /tmp/gamera.tar.gz -C /tmp
- sed -i -e 's/no_wx = False/no_wx = True/' /tmp/gamera-3.4.2/setup.py
- pip install --upgrade pip
- pip install -vvv /tmp/gamera-3.4.2/
- pip install -vvv pillow
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then pip install argparse; fi
- pip install python-xmp-toolkit
- pip install -vvv https://github.com/escaped/pyexiv2/archive/master.zip
script:
- nosetests -v
- grep -r -l ft=rst doc/ | xargs -t -n1 -I{} rst2pseudoxml.py --strict {} /dev/null

# vim:ts=2 sts=2 sw=2 et
