language: python
python:
- "2.6"
- "2.7"
addons:
  apt:
    packages:
    - djvulibre-bin
    - exiv2
    - libboost-python-dev
    - libexempi3
    - libexiv2-dev
    - libpng-dev
    - libtiff4-dev
    - libxml2-utils
    - minidjvu
cache:
  directories:
  - $HOME/.cache
  - $HOME/.ccache
install:
- export PATH="/usr/lib/ccache:$PATH"
- pip install docutils
- pip install pygments
- wget -c http://sourceforge.net/projects/gamera/files/gamera/gamera-3.4.2/gamera-3.4.2.tar.gz -O ~/.cache/gamera-3.4.2.tar.gz
- tar -xvzf ~/.cache/gamera-3.4.2.tar.gz
- sed -i -e 's/no_wx = False/no_wx = True/' gamera-3.4.2/setup.py
- pip install --upgrade pip
- pip install -vvv gamera-3.4.2/
- pip install -vvv pillow
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then pip install argparse; fi
- pip install python-xmp-toolkit
- pip install -vvv https://github.com/escaped/pyexiv2/archive/master.zip
script:
- nosetests -v
- grep -r -l ft=rst doc/ | xargs -t -n1 -I{} rst2xml.py --strict {} /dev/null
- xmllint --noout --valid doc/*.xml

# vim:ts=2 sts=2 sw=2 et
