language: python
python:
- "2.6"
- "2.7"
addons:
  apt:
    packages:
    - djvulibre-bin
    - exiv2
    - libboost-python-dev
    - libexempi3
    - libexiv2-dev
    - libpng-dev
    - libtiff4-dev
    - libxml2-utils
    - minidjvu
cache:
  directories:
  - $HOME/.cache
  - $HOME/.ccache
env:
- GAMERA_VERSION=3.4.3
install:
- export PATH="/usr/lib/ccache:$PATH"
- pip install --upgrade pip
- wget -c https://github.com/hsnr-gamera/gamera/releases/download/$GAMERA_VERSION/gamera-${GAMERA_VERSION}.tar.gz -O ~/.cache/gamera-${GAMERA_VERSION}.tar.gz
- tar -xvzf ~/.cache/gamera-${GAMERA_VERSION}.tar.gz
- sed -i -e 's/no_wx = False/no_wx = True/' gamera-${GAMERA_VERSION}/setup.py
- ( cd gamera-${GAMERA_VERSION}/ && python setup.py install )
- rm -r gamera-${GAMERA_VERSION}/
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then PILLOW_VERSION=3.4.2; fi
- pip install --verbose pillow${PILLOW_VERSION:+==$PILLOW_VERSION}
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then pip install argparse; fi
- pip install python-xmp-toolkit
- pip install --verbose git+https://github.com/escaped/pyexiv2
- pip install pydiatra
- pip install pyflakes
- pip install docutils
- pip install pygments
script:
- nosetests -v
- private/run-pydiatra
- private/run-pyflakes
- private/check-rst
- xmllint --noout --valid doc/*.xml

# vim:ts=2 sts=2 sw=2 et
