import wx
from _typeshed import Incomplete

class ExpertSettingPanel(wx.Panel):
    genericWidgets: Incomplete
    selectionWidgets: Incomplete
    weightingWidgets: Incomplete
    childWidgets: Incomplete
    def __init__(self, parent, id) -> None: ...
    def GetAllSettingWidgets(self): ...
    def AddChildToParent(self, parent, child) -> None: ...
    def BindEvent(self, event, function, widgetsList) -> None: ...
    def OnCheckBox(self, event) -> None: ...
    def OnRadioButton(self, event) -> None: ...
