from gamera.gui.gaoptimizer.SettingsPanel import *
from gamera.gui.gaoptimizer.StatusPanel import *
from gamera.gui.gaoptimizer.ResultPanel import *
import wx
from _typeshed import Incomplete
from gamera import knnga as knnga
from gamera.gui import gui_util as gui_util

class OptimizerFrame(wx.Frame):
    classifier: Incomplete
    settingsFilename: Incomplete
    notebook: Incomplete
    settingsPanel: Incomplete
    statusPanel: Incomplete
    resultPanel: Incomplete
    timer: Incomplete
    def __init__(self, parent, id, title) -> None: ...
    def CreateFileMenu(self): ...
    def CreateClassifierMenu(self): ...
    def EnableControls(self, flag: bool = ...) -> None: ...
    def OnTimerUpdate(self, event) -> None: ...
    def UpdatePanels(self) -> None: ...
    def SetClassifiers(self) -> None: ...
    def CopyClassifier(self, classifier): ...
    def OnOpenXML(self, event) -> None: ...
    def OnOpenClassifier(self, event) -> None: ...
    def OnSaveXML(self, event) -> None: ...
    def OnSaveXMLAs(self, event) -> None: ...
    def OnExit(self, event): ...
    def OnCopyClassifier(self, event) -> None: ...
    def OnIntoGameraGUI(self, event) -> None: ...
    def OnLoadSettings(self, event) -> None: ...
    def OnChangeFeatures(self, event) -> None: ...
    def OnResetSelections(self, event) -> None: ...
    def OnResetWeights(self, event) -> None: ...
