import wx
from _typeshed import Incomplete
from gamera import knnga as knnga

class ResultPanel(wx.ScrolledWindow):
    frame: Incomplete
    bars: Incomplete
    def __init__(self, parent, id, frame) -> None: ...
    def initResultsWidgets(self) -> None: ...
    def Update(self) -> None: ...
    def UpdateResultWidgets(self) -> None: ...
