import wx.html
from _typeshed import Incomplete

IS_WXP4: Incomplete

def resize_window_virtual(sizer, window) -> None: ...
def create_help_display(parent, docstring): ...
def configure_size_small_height(grid_sizer, window, min_width, client_area) -> None: ...
def configure_size_normal_height(grid_sizer, window, min_width, min_height) -> None: ...

class Calltip(wx.html.HtmlWindow):
    message_displayed: bool
    cache: Incomplete
    def __init__(self, parent: Incomplete | None = ..., id: int = ...) -> None: ...
    def display(self, calltip) -> None: ...
    def OnLinkClicked(self, link) -> None: ...

def configure_shell_auto_completion(shell) -> None: ...
def set_dialog_style(dialog) -> None: ...
def configure_icon_display_style(): ...
def configure_print_dialog_data(dialog_data) -> None: ...
def register_get_first_child(tree_ctrl_class): ...
def register_set_scrollbars(image_display_class) -> None: ...
def set_grid_line_colour(grid) -> None: ...
def register_renderer_access(multi_image_display_class): ...
def init_image_handlers() -> None: ...
def set_control_down(key_event) -> None: ...

DropTarget: Incomplete
Validator: Incomplete
GridCellRenderer: Incomplete
SplashScreen: Incomplete
SPLASH_CENTRE_ON_SCREEN: Incomplete
SPLASH_NO_TIMEOUT: Incomplete
ASSERT_SUPPRESS: Incomplete
FD_SAVE: Incomplete
EVT_GRID_CELL_CHANGED: Incomplete
FILE_DROP_DONE: Incomplete

def select_version() -> None: ...
def create_empty_image(width, height, clear: bool = ...): ...
def create_empty_bitmap(width, height, depth=...): ...
def create_icon_from_bitmap(bmp): ...
def create_image_from_stream(stream): ...
def create_bitmap_from_image(image): ...
def create_stock_cursor(id): ...
def set_tool_tip(window, tooltip_string) -> None: ...
def is_validator_silent(): ...
def begin_drawing(dc) -> None: ...
def end_drawing(dc) -> None: ...
def set_size(window, x, y, width, height, sizeFlags=...) -> None: ...
def create_data_format(format): ...
def get_window_size(window): ...
def add_img_list_icon(image_list, icon): ...
def insert_list_img_string_item(list_ctrl, index, label, icon) -> None: ...
def set_list_string_item(list_ctrl, index, column, label, image_id) -> None: ...
def get_list_event_item_index(list_event): ...
def get_tree_item_data(tree_ctrl, item): ...
def set_tree_item_data(tree_ctrl, item, data) -> None: ...
def extend_menu(menu, menu_item_id, item, sub_menu) -> None: ...
def handle_event_0(event_handler, event, callable) -> None: ...
def handle_event_1(event_handler, event, callable, id1=...) -> None: ...
def handle_event_2(event_handler, event, callable, id1=..., id2=...) -> None: ...
def handle_timer_event(event_handler, callable, timer_id) -> None: ...
