from types import *
import wx
from _typeshed import Incomplete
from gamera import util as util
from gamera.config import config as config
from gamera.gui import compat_wx as compat_wx

colors: Incomplete
color_number: int

def get_color(number): ...
def message(message) -> None: ...
def are_you_sure_dialog(message, parent: Incomplete | None = ...): ...
def build_menu(parent, menu_spec): ...

NUM_RECENT_FILES: int

class FileDialog(wx.FileDialog):
    last_directory: Incomplete
    extensions: Incomplete
    def __init__(self, parent, extensions: str = ..., multiple: int = ...) -> None: ...
    def show(self): ...

class OpenFileDialog(FileDialog): ...
class SaveFileDialog(FileDialog): ...

def open_file_dialog(parent, extensions: str = ..., multiple: int = ...): ...
def save_file_dialog(parent, extensions: str = ...): ...
def directory_dialog(parent, create: int = ...): ...

class ProgressBox:
    progress_box: Incomplete
    done: int
    def __init__(self, message, length: int = ..., numsteps: int = ...) -> None: ...
    def __del__(self) -> None: ...
    def add_length(self, l) -> None: ...
    def set_length(self, l) -> None: ...
    def step(self) -> None: ...
    def update(self, num, den) -> None: ...
    def kill(self) -> None: ...

def docstring_to_html(docstring): ...
def code_block(name, arguments, options, content, lineno, content_offset, block_text, state, state_machine): ...
