from gamera.core import *
from gamera.args import *
from _typeshed import Incomplete
from gamera import plugin as plugin, util as util
from gamera.gui import compat_wx as compat_wx, gui_util as gui_util, var_name as var_name

EXECUTE_MODE: int
HELP_MODE: int
shell: Incomplete

def set_shell(sh) -> None: ...
def set_shell_frame(sf) -> None: ...
def members_for_menu(self): ...
def methods_for_menu(self): ...

class ImageMenu:
    shell: Incomplete
    locals: Incomplete
    mode: Incomplete
    parent: Incomplete
    images: Incomplete
    image_name: Incomplete
    did_something: int
    def __init__(self, parent, x, y, images_, name_: Incomplete | None = ..., shell_: Incomplete | None = ..., mode=..., extra_methods=...) -> None: ...
    def get_id(self): ...
    functions: Incomplete
    def create_menu(self, members, methods, type, type_name, extra_methods): ...
    def create_methods(self, methods, menu): ...
    def create_extra_methods(self, methods, menu): ...
    def get_shell(self): ...
    def OnCreateReference(self, event) -> None: ...
    def OnCreateCopy(self, event) -> None: ...
    def OnDeleteImage(self, event) -> None: ...
    def get_function_call(self, sh, function): ...
    def get_result_name(self, function, dict): ...
    def OnPopupFunction(self, event) -> None: ...
