import wx
from _typeshed import Incomplete
from gamera.gui import compat_wx as compat_wx, gamera_icons as gamera_icons

ButtonClass: Incomplete
ToggleButtonClass: Incomplete

class ToolBar(wx.Panel):
    controls: Incomplete
    layout_update_controls: Incomplete
    sizer: Incomplete
    def __init__(self, parent, id: int = ..., hideable: int = ...) -> None: ...
    def AddSimpleTool(self, id, bitmap, help_string, callback: Incomplete | None = ..., toggle: int = ...): ...
    def AddMenuTool(self, id, text, help_string, callback: Incomplete | None = ..., toggle: int = ...): ...
    def AddControl(self, control) -> None: ...
    def AddSeparator(self) -> None: ...
    def OnHideToolbar(self, event) -> None: ...
    def OnShowToolbar(self, event) -> None: ...
