from _typeshed import Incomplete
from optparse import OptionParser, make_option as make_option
from os.path import expanduser as expanduser, isfile as isfile, join as join, split as split
from sys import platform as platform

class ConfigOptionParser(OptionParser):
    default_options: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def add_option(self, *args, **kwargs) -> None: ...  # type: ignore[override]
    def add_options(self, l) -> None: ...
    def get_config_files(self): ...
    def parse_args(self, args=...): ...
    def get(self, item): ...
    def set(self, item, val): ...
    def reparse_args(self): ...
    def get_free_args(self): ...
